stages:
  - build

server-build:
  stage: build
  image: debian:stretch-slim
  before_script:
    - apt update -qq
    - apt install -yqq curl sudo
    - useradd eggshell
    - usermod -aG sudo eggshell
    - mkdir -p /home/eggshell
    - chown -R eggshell:eggshell /home/eggshell
  script:
    - bash debian-server.sh

std-build:
  stage: build
  image: debian:stretch
  before_script:
    - apt update -qq
    - apt install -yqq curl sudo
    - useradd eggshell
    - usermod -aG sudo eggshell
    - mkdir -p /home/eggshell
    - chown -R eggshell:eggshell /home/eggshell
  script:
    - bash debian-laptop.sh
